### ISSUE TITLE
Standard for compiling/running benchmarks

### ISSUE THREAD

**Issue by leonardoalt** [eth-sc-comp/benchmarks#2]
We've agreed so far that the benchmark inputs would be Solidity files, and the properties would be written as assertions. We could also standardize the compilation by making the input a Foundry repo, since many of the tools do support that. What do you think @ehildenb ? For now this would be to standardize compilation and the bytecode artifacts. The assertions would still be coming from the tested benchmark and not as Foundry test harnesses.

**Comment by msooseth** [comment]
The system is now running K-framework without a hitch. We have also invited a number of people from Runtime Verification to the repo to make sure the folks there are onboard :) I am closing because I think this has become stale, thanks to K-framework being integrated.
