### ISSUE TITLE
Halmos fails to build after `nix flake update`

### ISSUE THREAD

**Issue by geo2a** [eth-sc-comp/benchmarks#32]
I'm trying to banchmark the current versions of tools, but I'm struggling to update Halmos in the nix flake.

When I do `nix flake update`, I get new `nixpkgs` and unfortunately the changes seem so massive they make the derivation for Halmos in `flake.nix` completely outdated, resulting in the following error:

```
error: builder for '/nix/store/wjqanmm2xyang01c58sfkyl9khh49f6r-halmos-0.0.0.drv' failed with exit code 1;
       last 10 log lines:
       > writing entry points to src/halmos.egg-info/entry_points.txt
       > writing requirements to src/halmos.egg-info/requires.txt
       > writing top-level names to src/halmos.egg-info/top_level.txt
       > writing manifest file 'src/halmos.egg-info/SOURCES.txt'
       > reading manifest file 'src/halmos.egg-info/SOURCES.txt'
       > adding license file 'LICENSE'
       > writing manifest file 'src/halmos.egg-info/SOURCES.txt'
       >
       > ERROR Missing dependencies:
       >     setuptools_scm[toml]>=6.2
       For full logs, run 'nix-store -l /nix/store/wjqanmm2xyang01c58sfkyl9khh49f6r-halmos-0.0.0.drv'.
error: 1 dependencies of derivation '/nix/store/5x6mg9x3nzfs38fwa01qyca3cc34vnwq-nix-shell-env.drv' failed to build
```

Does Halmos use `poetry`? Perhaps we could nixify it with [poetry2nix](https://github.com/nix-community/poetry2nix) and thus make it much more straightforward to use run this benchmark.

**Comment by karmacoma-eth** [comment]
halmos does not use poetry, it just relies on pyproject.toml and we normally just need to run `pip install halmos`. 

@daejunpark do you know if this part of our pyproject.toml is still needed?

```
[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```

**Comment by d-xo** [comment]
I think this should fix the build for the latest halmos: https://github.com/eth-sc-comp/benchmarks/pull/33

**Comment by geo2a** [comment]
Thanks a lot @d-xo, #33 does indeed fix the build!

However, it seems like the CLI of `halmos` has changed significantly, and `tools/halmos.sh` script needs updating.

I suppose we can merge #33 and deal with the interface update in a separate PR!

**Comment by karmacoma-eth** [comment]
yes, I'll take a look at tools/halmos.sh
